### ISSUE TITLE
[QUESTION] Can you provide the tailwind.config.js you used for this?

### ISSUE THREAD

**Issue by waterbuckit** [TypedProject/tsed-formio#9]
I'm having issues regarding particular classnames not existing, for example "border-1" is not a default tailwind classname, I've added it but I'm still getting issues about not having the text colours for primary/secondary even though I've added them.

Just want to make sure I'm doing everything right.

**Comment by Romakita** [comment]
Hello @waterbuckit 
As you can see, the package is pretty recent and need some improvement. Your feedback are welcome.
The used file is here: https://github.com/TypedProject/tsed-formio/blob/master/packages/tailwind/tailwind.config.js

See you
Romain

**Comment by waterbuckit** [comment]
Thanks for the package though - been meaning to do something similar for a long time. I found it after I posted this which is why I closed it aha! I got it working, but I noticed a small issue with tabs, assuming you are intending to have the package reflect how formio looks in its default bootstrap configuration:

![2021-03-11-140641_1896x1015_scrot](https://user-images.githubusercontent.com/22277521/110799665-5262f900-8273-11eb-875f-234c8c2d3cd9.png)

Thanks again
